spring:
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/reactive}
    username: ${POSTGRES_USER:reactive}
    password: ${POSTGRES_PASSWORD:reactive}
  flyway:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/reactive}
    user: ${DB_MIGRATION_USER:reactive}
    password: ${DB_MIGRATION_PASSWORD:reactive}
  r2dbc:
    url: ${POSTGRES_URL:r2dbc:postgresql://localhost:5432/reactive}
    username: ${DB_MIGRATION_USER:reactive}
    password: ${DB_MIGRATION_PASSWORD:reactive}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
          lob.non_contextual_creation: true
        connection.autocommit: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
